# Generated by Django 2.2.13 on 2021-03-12 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='valor',
        ),
    ]
