# Generated by Django 2.2.13 on 2021-03-12 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_venda_valor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venda',
            old_name='produto',
            new_name='produto_id',
        ),
    ]
