# Generated by Django 3.1.7 on 2021-03-15 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210315_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='venda',
            old_name='user_id',
            new_name='user',
        ),
    ]
