# Generated by Django 3.1.7 on 2021-03-18 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210315_2046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venda',
            old_name='produto_id',
            new_name='produto',
        ),
    ]
